apiVersion: v1
kind: Service
metadata:
        name: vproapp-service
spec:
        ports:
                - port: 80
                  targetPort: vproapp-port
                  Protocol: TCP
        selector:
                app: vproapp
        Type: LoadBalancer      
